name: CEJ Design
favicon: null
layout_spectrum: 0.90533
typography_spectrum: 0.18549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8d9089'
    - '#756e5e'
    - '#514d41'
    - '#805334'
    - '#202423'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
